/**********************************************************************
 * Liquid Glass TOOLBAR for After Effects — physics refraction via a
 * BAKED displacement map (no plugins needed; uses the stock
 * "Displacement Map" effect).
 *
 * You need the two baked PNGs (generated by bake_ae_assets.js):
 *     ae_displacement.png   (the refraction map)
 *     ae_surface.png        (rim / specular / shadow / icons overlay)
 *
 * RUN:  File › Scripts › Run Script File…  ›  this file
 *       …then pick the two PNGs when prompted.
 *
 * The glass sits at the comp centre and REFRACTS + frosts whatever
 * layers are BELOW the "Glass / Refraction" adjustment layer. Put your
 * content there (above the DEMO layers). Frost amount = the "Frost"
 * slider on the "Controls" null.
 *
 * To move/resize the glass: it's a fixed-position element (the map is
 * baked for the centre). For a different spot/size, change cap.* in
 * bake_ae_assets.js and re-bake, or ask for a re-bake.
 *********************************************************************/

(function liquidGlassToolbarAE() {

    var W = 900, H = 440, FPS = 30, DUR = 6;
    var CX = W / 2, CY = H / 2;
    var PW = 436, PH = 132, PR = 66;
    var MAXDISP = 48;                 // must match bake_ae_assets.js output

    // ---- pick the baked assets ----
    alert("Liquid Glass (AE) — pick the two baked PNGs next:\n" +
          "1) ae_displacement.png\n2) ae_surface.png");
    var dispFile = File.openDialog("Select ae_displacement.png");
    if (!dispFile) return;
    var surfFile = File.openDialog("Select ae_surface.png");
    if (!surfFile) return;

    app.beginUndoGroup("Build Liquid Glass Toolbar (AE)");

    function imp(file) { return app.project.importFile(new ImportOptions(file)); }
    var dispItem = imp(dispFile), surfItem = imp(surfFile);

    // ---- helpers ----
    function setExpr(p, e) { if (p) p.expression = e; }
    function pos(L) { return L.property("ADBE Transform Group").property("ADBE Position"); }
    function setPos(L, p) { pos(L).setValue(p); }
    function setOp(L, v) { L.property("ADBE Transform Group").property("ADBE Opacity").setValue(v); }
    function roundedRectShape(cx, cy, w, h, r) {
        var k = r * 0.5523, l = cx-w/2, rt = cx+w/2, t = cy-h/2, b = cy+h/2, s = new Shape();
        s.vertices = [[l+r,t],[rt-r,t],[rt,t+r],[rt,b-r],[rt-r,b],[l+r,b],[l,b-r],[l,t+r]];
        s.inTangents  = [[-k,0],[0,0],[0,-k],[0,0],[k,0],[0,0],[0,k],[0,0]];
        s.outTangents = [[0,0],[k,0],[0,0],[0,k],[0,0],[-k,0],[0,0],[0,-k]];
        s.closed = true; return s;
    }
    function addMask(L, shape, feather) {
        var m = L.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
        m.property("ADBE Mask Shape").setValue(shape);
        if (feather != null) m.property("ADBE Mask Feather").setValue([feather, feather]);
        return m;
    }
    function addRamp(L, p1, c1, p2, c2) {
        var fx = L.property("ADBE Effect Parade").addProperty("ADBE Ramp");
        fx.property("ADBE Ramp-0001").setValue(p1); fx.property("ADBE Ramp-0002").setValue(c1);
        fx.property("ADBE Ramp-0003").setValue(p2); fx.property("ADBE Ramp-0004").setValue(c2); return fx;
    }

    var comp = app.project.items.addComp("Liquid Glass Toolbar (AE)", W, H, 1, DUR, FPS);
    comp.bgColor = [0, 0, 0]; comp.openInViewer();
    function solid(name, color) { return comp.layers.addSolid(color, name, W, H, 1); }

    // ---- Controls null (Frost slider) ----
    var controls = comp.layers.addNull(DUR); controls.name = "Controls";
    setPos(controls, [26, 26]);
    var cFx = controls.property("ADBE Effect Parade");
    var frostFx = cFx.addProperty("ADBE Slider Control"); frostFx.name = "Frost"; frostFx.property(1).setValue(14);

    // ---- DEMO content (delete & put your own layers here, BELOW the refraction) ----
    solid("DEMO bg", [0.02, 0.02, 0.02]);
    var green = solid("DEMO green card", [0.3, 0.6, 0.28]);
    addMask(green, roundedRectShape(450, 560, 840, 760, 78), 1.5);
    addRamp(green, [450, 175], [0.42, 0.74, 0.34], [450, 470], [0.15, 0.40, 0.16]);
    var dots = comp.layers.addShape(); dots.name = "DEMO dots";
    (function(){ var c=dots.property("ADBE Root Vectors Group").addProperty("ADBE Vector Group").property("ADBE Vectors Group");
        var cols=[[0.2,0.55,1],[0.1,0.82,0.75],[0.62,0.38,1],[1,0.45,0.5],[0.3,0.85,0.4],[1,0.8,0.2]];
        for(var i=0;i<cols.length;i++){var g=c.addProperty("ADBE Vector Group").property("ADBE Vectors Group");
            var e=g.addProperty("ADBE Vector Shape - Ellipse");e.property("ADBE Vector Ellipse Size").setValue([34,34]);
            e.property("ADBE Vector Ellipse Position").setValue([120+i*130,250]);
            g.addProperty("ADBE Vector Graphic - Fill").property("ADBE Vector Fill Color").setValue(cols[i]);}})();

    // ---- displacement source (hidden map layer) ----
    var dispLayer = comp.layers.add(dispItem); dispLayer.name = "Glass / Disp (map)";
    setPos(dispLayer, [CX, CY]); dispLayer.enabled = false;

    // ---- REFRACTION adjustment: Displacement Map + frost blur, masked to pill ----
    var refr = solid("Glass / Refraction", [0, 0, 0]); refr.adjustmentLayer = true;
    addMask(refr, roundedRectShape(CX, CY, PW + 4, PH + 4, PR), 2);
    var dm = refr.property("ADBE Effect Parade").addProperty("ADBE Displacement Map");
    function dmp(name, idx) { var p=null; try{p=dm.property(name);}catch(e){} if(!p){try{p=dm.property(idx);}catch(e2){}} return p; }
    var mapSel = dmp("Displacement Map Layer", 1); if (mapSel) mapSel.setValue(dispLayer.index);
    var uh = dmp("Use For Horizontal Displacement", 2); if (uh) uh.setValue(1); // Red
    var mh = dmp("Max Horizontal Displacement", 3);     if (mh) mh.setValue(MAXDISP);
    var uv = dmp("Use For Vertical Displacement", 4);   if (uv) uv.setValue(2); // Green
    var mv = dmp("Max Vertical Displacement", 5);       if (mv) mv.setValue(MAXDISP);
    var bh = dmp("Displacement Map Behavior", 6);       if (bh) bh.setValue(1); // Center Map
    var gb; try { gb = refr.property("ADBE Effect Parade").addProperty("ADBE Gaussian Blur 2"); }
    catch (e) { gb = refr.property("ADBE Effect Parade").addProperty("ADBE Gaussian Blur"); }
    setExpr(gb.property(1), 'thisComp.layer("Controls").effect("Frost")("Slider")');
    try { gb.property(3).setValue(1); } catch (e) {}

    // ---- surface overlay (rim / specular / shadow / icons) ----
    var surfLayer = comp.layers.add(surfItem); surfLayer.name = "Glass / Surface";
    setPos(surfLayer, [CX, CY]);

    // soft drop shadow under the pill (on the content)
    var shadow = solid("Glass / Drop Shadow", [0, 0, 0]);
    addMask(shadow, roundedRectShape(CX, CY + 14, PW + 8, PH + 8, PR), 26); setOp(shadow, 30);
    shadow.moveAfter(refr); // just below the refraction/surface, above content

    app.endUndoGroup();

    alert("Liquid Glass Toolbar (AE) — built ✨\n\n" +
          "• Physics refraction via the baked displacement map + AE's\n" +
          "  Displacement Map effect (no plugins).\n" +
          "• It refracts + frosts the layers BELOW 'Glass / Refraction'.\n" +
          "  Put your content there (above the DEMO layers).\n" +
          "• 'Controls' null: Frost = blur amount.\n\n" +
          "Fixed position (map baked for centre). For another position/size,\n" +
          "re-bake with bake_ae_assets.js (change cap.*) and re-import.");

})();
